language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - andres.grisalesg@udea.edu.co
addons:
  sonarcloud:
    organization: "organization-test-eplatform"
    token: $SONAR
before_install:
  - chmod +x gradlew
script:
  - ./gradlew sonarqube
  - ./gradlew clean build