language: java
branches:
  only:
    - develop
    - master
notifications:
  email:
    recipients:
      - andres.grisalesg@udea.edu.co
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build